# Optionnel: Streamlit dans K3s (si tu ne veux pas le lancer standalone sur le serveur)
# Nginx: / -> http://127.0.0.1:30501

apiVersion: v1
kind: Service
metadata:
  name: streamlit
spec:
  selector:
    app: streamlit
  type: NodePort
  ports:
    - name: http
      port: 8501
      targetPort: 8501
      nodePort: 30501

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: streamlit
spec:
  replicas: 1
  selector:
    matchLabels:
      app: streamlit
  template:
    metadata:
      labels:
        app: streamlit
    spec:
      containers:
        - name: streamlit
          image: REPLACE_ME/mlops-streamlit:latest
          ports:
            - containerPort: 8501
          env:
            # Streamlit appelle lâ€™API via le NodePort local (ou via ton Nginx https://.../api)
            - name: GATEWAY_API_URL
              value: "http://gateway-api:8080"
            - name: PROMETHEUS_URL
              value: "http://prometheus:9090"
            - name: GRAFANA_URL
              value: "http://grafana:3000/grafana"
          readinessProbe:
            httpGet:
              path: /_stcore/health
              port: 8501
            initialDelaySeconds: 10
            periodSeconds: 10
