[project]
name = "mlops-construction-cost-prediction"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "dvc>=3.66.1",
    "joblib>=1.5.3",
    "mlflow>=3.9.0",
    "pandas>=2.3.3",
]
