apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: mlops
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s

    scrape_configs:
      - job_name: 'gateway-api'
        static_configs:
          - targets: ['gateway-api:8080']
      - job_name: 'inference-api'
        static_configs:
          - targets: ['inference-api:8000']
