apiVersion: v1
kind: Secret
metadata:
  name: mlops-secrets
  namespace: mlops
type: Opaque
stringData:
  POSTGRES_USER: "airflow"
  POSTGRES_PASSWORD: "airflow"
  POSTGRES_DB: "airflow"
  AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: "postgresql+psycopg2://airflow:airflow@postgres/airflow"
  AIRFLOW_USER: "admin"
  AIRFLOW_PASSWORD: "admin"
  INFERENCE_INTERNAL_TOKEN: "mlops-internal-token-2024"
  GATEWAY_DB_PASSWORD: "gateway"
  JWT_SECRET_KEY: "mlops-jwt-secret-key-2024"
