global:
  scrape_interval: 3s
  evaluation_interval: 15s # Fréquence à laquelle les règles d'alerte sont évaluées

rule_files:
  - 'rules/alert_rules.yml' # Fichier contenant les règles d'alerte personnalisées
scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
  - job_name: 'nginx-exporter'
    static_configs:
      # Cible à scraper : l'exporter Nginx
      - targets: ['nginx_exporter:9113']
  - job_name: 'solafune-api'
    static_configs:
      - targets: ['solafune-api:8000']