global:
  scrape_interval: 5s
  evaluation_interval: 15s # Frequence d'evaluation des alertes

rule_files:
  - "rules/alert_rules.yml"

scrape_configs:

  - job_name: "prometheus"
    static_configs:
      - targets: ["prometheus:9090"]

  - job_name: "gateway-api"
    static_configs:
      - targets: ["gateway-api:8100"]

  - job_name: "inference-api"
    static_configs:
      - targets: ["inference-api:8000"]

  - job_name: "nginx-exporter"
    static_configs:
      - targets: ["nginx-exporter:9113"]

  - job_name: "node-exporter"
    static_configs:
      - targets: ["node-exporter:9100"]
